apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-prod
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/marrober/myapp
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-prod
  target:
    kind: Service
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-prod
  target:
    kind: Route
    name: myapp-route
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-prod
  target:
    kind: Namespace
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-prod
  target:
    kind: RoleBinding
    name: argocd-admin
bases:
- ../base/main
- ../base/01-rolebindings
images:
- name: quay.io/marrober/myapp
  newTag: 6322-rbbs9
